
export const themeConfig: Record<string, string> = {
    'theme.light.background': '--background',
    'theme.light.foreground': '--foreground',
    'theme.light.card': '--card',
    'theme.light.card-foreground': '--card-foreground',
    'theme.light.popover': '--popover',
    'theme.light.popover-foreground': '--popover-foreground',
    'theme.light.primary': '--primary',
    'theme.light.primary-foreground': '--primary-foreground',
    'theme.light.secondary': '--secondary',
    'theme.light.secondary-foreground': '--secondary-foreground',
    'theme.light.muted': '--muted',
    'theme.light.muted-foreground': '--muted-foreground',
    'theme.light.accent': '--accent',
    'theme.light.accent-foreground': '--accent-foreground',
    'theme.light.destructive': '--destructive',
    'theme.light.destructive-foreground': '--destructive-foreground',
    'theme.light.border': '--border',
    'theme.light.input': '--input',
    'theme.light.ring': '--ring',

    'theme.dark.background': '--background',
    'theme.dark.foreground': '--foreground',
    'theme.dark.card': '--card',
    'theme.dark.card-foreground': '--card-foreground',
    'theme.dark.popover': '--popover',
    'theme.dark.popover-foreground': '--popover-foreground',
    'theme.dark.primary': '--primary',
    'theme.dark.primary-foreground': '--primary-foreground',
    'theme.dark.secondary': '--secondary',
    'theme.dark.secondary-foreground': '--secondary-foreground',
    'theme.dark.muted': '--muted',
    'theme.dark.muted-foreground': '--muted-foreground',
    'theme.dark.accent': '--accent',
    'theme.dark.accent-foreground': '--accent-foreground',
    'theme.dark.destructive': '--destructive',
    'theme.dark.destructive-foreground': '--destructive-foreground',
    'theme.dark.border': '--border',
    'theme.dark.input': '--input',
    'theme.dark.ring': '--ring',
};
