'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/ai-title-generator.ts';
import '@/ai/flows/ai-query-comparlify-chatbot.ts';
import '@/ai/flows/ai-course-outliner.ts';
import '@/ai/flows/ai-video-scripter.ts';
import '@/ai/flows/ai-lesson-summarizer.ts';
import '@/ai/flows/ai-quiz-generator.ts';
import '@/ai/flows/ai-audience-persona-generator.ts';
import '@/ai/flows/ai-course-description-writer.ts';
import '@/ai/flows/ai-learning-objectives-generator.ts';
import '@/ai/flows/ai-email-subject-line-generator.ts';
import '@/ai/flows/ai-social-media-post-generator.ts';
import '@/ai/flows/ai-faq-generator.ts';
import '@/ai/flows/ai-analogy-generator.ts';
import '@/ai"flows/ai-generic-content-generator.ts';
import '@/ai/flows/ai-image-generator.ts';
import '@/ai/flows/ai-logo-generator.ts';
import '@/ai/flows/ai-course-prerequisites-generator.ts';
import '@/ai/flows/ai-content-repurposer.ts';
import '@/ai/flows/ai-ice-breaker-generator.ts';
import '@/ai/flows/ai-promotional-video-ideas-generator.ts';
